In [6]:
import pandas as pd

In [8]:
data_ethio = {
    "Name": ["Abel", "Hana", "Dawit", "Selam", "Biruk", "Meklit", "Tesfaye", "Ruth", "Henok", "Liya",
             "Nahom", "Saron", "Bereket", "Betelhem", "Yonas"],

    "Age": [20, 21, 22, 19, 23, 20, 21, 22, 24, 20,
            23, 21, 22, 20, 24],

    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F",
               "M", "F", "M", "F", "M"],

    "Result": ["Pass", "Pass", "Pass", "Fail", "Pass", "Pass", "Pass", "Pass", "Fail", "Pass",
               "Pass", "Pass", "Fail", "Pass", "Pass"],

    "Score": [78, 82, 90, 55, 70, 88, 76, 91, 60, 80,
              85, 79, 65, 87, 74]
}

In [9]:
df_ethio = pd.DataFrame(data_ethio, index=[f"STU_{i}" for i in range(1, 16)])
df_ethio

            Name  Age Gender Result  Score
STU_1       Abel   20      M   Pass     78
STU_2       Hana   21      F   Pass     82
STU_3      Dawit   22      M   Pass     90
STU_4      Selam   19      F   Fail     55
STU_5      Biruk   23      M   Pass     70
STU_6     Meklit   20      F   Pass     88
STU_7    Tesfaye   21      M   Pass     76
STU_8       Ruth   22      F   Pass     91
STU_9      Henok   24      M   Fail     60
STU_10      Liya   20      F   Pass     80
STU_11     Nahom   23      M   Pass     85
STU_12     Saron   21      F   Pass     79
STU_13   Bereket   22      M   Fail     65
STU_14  Betelhem   20      F   Pass     87
STU_15     Yonas   24      M   Pass     74

In [10]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
496,497,1,1,"Eustis, Miss. Elizabeth Mussey",female,54.0,1,0,36947,78.2667,D20,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C
460,461,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [15]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [17]:
median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)

In [19]:
most_common = df["Embarked"].mode()[0]
df["Embarked"] = df["Embarked"].fillna(most_common)

In [20]:
df = df.drop(columns=["Cabin"])

In [21]:
df = df.drop_duplicates()

In [23]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [25]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [26]:
df.groupby("Pclass")["Age"].mean()

Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64

In [27]:
df["Age_Category"] = pd.cut(df["Age"],
                           bins=[0, 10, 18, 30, 50, 100],
                           labels=["Kid", "Teen", "Young", "Middle", "Old"])

df.groupby("Age_Category")["Survived"].mean()

/tmp/ipykernel_1500/115498689.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Age_Category")["Survived"].mean()

Age_Category
Kid       0.593750
Teen      0.426667
Young     0.331096
Middle    0.423237
Old       0.343750
Name: Survived, dtype: float64

In [28]:
df.query('Sex == "female" and Survived == 1')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Category
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Middle
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Young
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Middle
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,Young
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,Teen
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,C,Young
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,C,Teen
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Old
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,S,Young
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Young

In [29]:
df[(df["Age"] <= 10) & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Category
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,S,Kid
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,C,Kid
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,S,Kid
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,S,Kid
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,S,Kid
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,S,Kid
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,S,Kid
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,S,Kid
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,S,Kid
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,S,Kid
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,S,Kid
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,S,Kid
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,S,Kid
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,S,Kid
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,S,Kid
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,C,Kid
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,S,Kid
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,S,Kid
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,C,Kid
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,C,Kid
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,S,Kid
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,S,Kid
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,S,Kid
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,S,Kid
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,S,Kid
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,S,Kid
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,C,Kid
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,C,Kid
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,S,Kid
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,S,Kid
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,S,Kid
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,S,Kid
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,S,Kid
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,S,Kid
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,C,Kid
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,C,Kid
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,S,Kid
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,S,Kid

In [30]:
df[(df["Pclass"] == 1) & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Category
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Middle
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Middle
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S,Old
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S,Young
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28.0,1,0,PC 17569,146.5208,C,Young
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,S,Middle
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,S,Middle
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Old
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Young
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,Young

Insignts

Female passengers had a higher survival rate compared to males. First-class passengers were more likely to survive than lower classes. Children had better survival chances, indicating priority during rescue. The highest survival combination was female passengers in first class.